### ISSUE TITLE
GUI not showing up in bloxfruit

### ISSUE THREAD

**Issue by AveriiasDoestwork** [Averiias/Universal-SilentAim#10]
Every time I try to inject using Scipt-ware the GUi does not show up in blox fruit

**Comment by Brayden330** [comment]
1st off who tf play blox fruit shitty ass game worst game in the world along with all the other anime games, Anyways its not just that shitty bloxfruit game I wish it was but it is every game.

**Comment by AveriiasDoestwork** [comment]
> 1st off who tf play blox fruit shitty ass game worst game in the world along with all the other anime games, Anyways its not just that shitty bloxfruit game I wish it was but it is every game.

Well what do you play?

**Comment by Brayden330** [comment]
> > 1st off who tf play blox fruit shitty ass game worst game in the world along with all the other anime games, Anyways its not just that shitty bloxfruit game I wish it was but it is every game.
> 
> Well what do you play?

I was messing with you but I do not like anime games but I don't hate them that much I just miss the classic games

**Comment by Brayden330** [comment]
Also possible fix
https://github.com/wally-rblx/LinoriaLib

**Comment by Brayden330** [comment]
loadstring(game:HttpGet('https://pastebin.com/raw/R0aN6JF7'))()

I also removed the watermark so click right ctrl or right shift to open the menu! I am not the maker of this I just fixed it!
