### ISSUE TITLE
Plss, update

### ISSUE THREAD

**Issue by Dragozs** [Averiias/Universal-SilentAim#11]
Not working in Blox Fruits :(

**Comment by AveriiasDoestwork** [comment]
Its patched I think, It doesn't work for other games either

**Comment by Yuuki1y** [comment]
It's not fixed, just the lib site that has a problem.

**Comment by Yuuki1y** [comment]
It's not fixed, just the lib site that has a problem.

**Comment by AveriiasDoestwork** [comment]
> It's not fixed, just the lib site that has a problem.

When will it be fixed?

**Comment by Yuuki1y** [comment]
> > It's not fixed, just the lib site that has a problem.
> 
> When will it be fixed?

loadstring(game:HttpGet("https://raw.githubusercontent.com/Yuuki1y/BFaimbot/main/UniversalAim"))()

**Comment by AveriiasDoestwork** [comment]
> > > It's not fixed, just the lib site that has a problem.
> > 
> > 
> > When will it be fixed?
> 
> loadstring(game:HttpGet("[https://raw.githubusercontent.com/Yuuki1y/BFaimbot/main/UniversalAim"))(](https://raw.githubusercontent.com/Yuuki1y/BFaimbot/main/UniversalAim%22))())

Thank you so much!

**Comment by Brayden330** [comment]
> It's not fixed, just the lib site that has a problem.

I fixed it

**Comment by Brayden330** [comment]
loadstring(game:HttpGet('https://pastebin.com/raw/R0aN6JF7'))()

I also removed watermark

**Comment by Dragozs** [comment]
Thank you guys. you are the best <3
