### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by MaguirePool** [Averiias/Universal-SilentAim#13]
The linoria hub has been removed in ur script "if not syn or not protectgui then
    getgenv().protectgui = function()end
end
local Library = loadstring(game:HttpGet('https://lindseyhost.com/UI/LinoriaLib.lua'))()
Library:SetWatermark("github.com/Averiias")" 

if u go to https://lindseyhost.com/UI/LinoriaLib.lua it will show account suspended so this is linoria hub problem any fix?

**Comment by Brayden330** [comment]
loadstring(game:HttpGet('https://pastebin.com/raw/R0aN6JF7'))()

I also removed the watermark so click right ctrl or right shift to open the menu! I am not the maker of this I just fixed it!

**Comment by MaguirePool** [comment]
thanks mate
