### ISSUE TITLE
First bug

### ISSUE THREAD

**Issue by AveriiasDoestwork** [Averiias/Universal-SilentAim#24]
Upon using method "Mouse.Hit/target" in Blox Fruit (executor: script-ware)

- Cannot click or use any special moves
- Once the script is disabled I can use click but not my special moves

**Comment by AveriiasDoestwork** [comment]
Here's a video showcasing the bug
https://streamable.com/y1n72s

**Comment by LordOfQuestions** [comment]
This bug of averiias not working on blox fruits started happening after the latest update of averiias it worked fine before , can you do a version of the old script to be available for us? it s less complicated , and another suggestion could please add an option to aim at the legs of the character too? it would be helpful.

**Comment by Averiias** [comment]
mouse.hit should work now, if it doesnt contact me on discord ave#6717
