### ISSUE TITLE
clicking/mouse not working and toggle

### ISSUE THREAD

**Issue by shindzoi** [Averiias/Universal-SilentAim#28]
the aimbot aint working clicking/mouse thingy and the toggle too fix it bro please :)

**Comment by shindzoi** [comment]
![Uploading Screenshot_36.png…]()

**Comment by Averiias** [comment]
your screenshot isnt loading

**Comment by shindzoi** [comment]
![Screenshot_36](https://user-images.githubusercontent.com/105586446/169467637-937d0fb2-9a66-4550-95bd-cad6a61619c8.png)

**Comment by shindzoi** [comment]
when i do the toggle thingy it dont work
and when enabled too

**Comment by shindzoi** [comment]
![Screenshot_37](https://user-images.githubusercontent.com/105586446/169468014-664a66f6-71f6-40e3-be39-f3c5de922247.png)
spamming alot still wont work

**Comment by shindzoi** [comment]
ALRIGHT FOUND THE LEGIT PROB
the toggle thingy wont work

**Comment by shindzoi** [comment]
nevermind i fixed it when i redownload my synapse. sorry for botherin
