### ISSUE TITLE
Raycast issue

### ISSUE THREAD

**Issue by Nopeisavalible** [Averiias/Universal-SilentAim#30]
After this script's update raycast acts like crazy - my camera flying around whole map if aimbot sees a target. Previous version doesn't have this problem (camera was static) so may you please fix this or at least send me the old one?

**Comment by Averiias** [comment]
most likely something related to the game you are playing

**Comment by Nopeisavalible** [comment]
Ok, maybe... May we check old script's version to be sure that's all the game problem? Then this issue will be solved. But if this will be script issue then you will be able to get any information and fix this.

**Comment by Nopeisavalible** [comment]
(How I said, script was working in this game before this update)

**Comment by Averiias** [comment]
link the game

**Comment by Nopeisavalible** [comment]
https://www.roblox.com/games/6937208251/Star-Wars-Battleground

**Comment by Nopeisavalible** [comment]
Any news?

**Comment by Nopeisavalible** [comment]
How about to read the issue before asking useless question? (sorry but deservedly)
That version what was made before script's update released some days ago (12?)

**Comment by Averiias** [comment]
Tested on a Feb13 version, the issue is game specific.
