### ISSUE TITLE
blue thingy on screen

### ISSUE THREAD

**Issue by sensaki** [Averiias/Universal-SilentAim#35]

**Comment by sensaki** [comment]
can u make it optional like make the blue thingy appear or dissepear

**Comment by sensaki** [comment]
![Screenshot_36](https://user-images.githubusercontent.com/107532371/173746009-248da406-3d70-4a2b-a799-65433a899d8e.png)

**Comment by acidumrifle** [comment]
yh, the script now works its just i press'leftAlt' nothing happens, i press 'alt gr' the blue thing just disappears,i mean yh it does show 'Github/.Averrias' but again i press 'leftalt' nothing happens can u fix this and maybe make the keybind to open the aimbot menu clearer(maybe something like 'ctrl') tysm for this script anyways very helpful, ur my heroes:))) (please fix it tho)

**Comment by 518401643** [comment]
It doesn't seem to be working.

**Comment by Averiias** [comment]
Resolved
