### ISSUE TITLE
It's not working. I hope you can fix it.

### ISSUE THREAD

**Issue by 518401643** [Averiias/Universal-SilentAim#36]
Don't know why it keeps Fov in the top left corner.

**Comment by TRex9981e** [comment]
same\

**Comment by cataclysmism** [comment]
Yep, stopped working for me today. Rather unfortunate considering this is probably the best silent aim but I hope they could fix it.

**Comment by Chell-source** [comment]
When will they fix this, i cant play my favorite roblox game without it.

**Comment by bruh2491** [comment]
Same here, it keeps the fov circle and silent aim target on the top left part of the screen for no reason.

**Comment by Averiias** [comment]
Resolved
